import os
import json
import time
import uuid
import re
# from xxlimited import Str
import psycopg2
from typing import TypedDict, List, Optional
from langgraph.graph import StateGraph, END
# from langchain_anthropic import ChatAnthropic
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.messages import HumanMessage, SystemMessage
import os
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from dotenv import load_dotenv

load_dotenv()  # must run before any Google client is created so GOOGLE_API_KEY is set

embedder = GoogleGenerativeAIEmbeddings(model="gemini-embedding-2-preview",output_dimensionality=1536)
# ============================================================
# 1. SETUP
# ============================================================

# os.environ["LANGCHAIN_TRACING_V2"] = "true"
os.environ["LANGCHAIN_PROJECT"] = "kafka-anomaly-agent"
# os.environ["LANGCHAIN_API_KEY"]  = "..."   # from .env
# os.environ["ANTHROPIC_API_KEY"]  = "..."

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=1)

sql_agent = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash", 
    temperature=0       # precise, deterministic — SQL must be exact
)

report_agent = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash", 
    temperature=1       # creative, narrative — reports should read well
)
# DB connection settings come from the environment (.env), never hardcoded.
DB_CONFIG = {
    "host":     os.getenv("DB_HOST", "localhost"),
    "port":     int(os.getenv("DB_PORT", "5432")),
    "user":     os.getenv("DB_USER", "postgres"),
    "password": os.getenv("DB_PASSWORD", ""),
    "dbname":   os.getenv("DB_NAME", "orders_db"),
}


def get_conn():
    return psycopg2.connect(**DB_CONFIG)


def get_readonly_conn():
    """Connection used to run LLM-generated SQL — read-only at the session level
    so an injected/hallucinated statement physically cannot mutate data."""
    conn = psycopg2.connect(**DB_CONFIG)
    conn.set_session(readonly=True, autocommit=True)
    return conn


# Statements the LLM is allowed to run. Anything else is rejected before execution.
_FORBIDDEN_SQL = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|ALTER|TRUNCATE|CREATE|GRANT|REVOKE|"
    r"COPY|MERGE|CALL|DO|VACUUM|EXECUTE)\b",
    re.IGNORECASE,
)


def is_safe_select(sql: str) -> bool:
    """Allow exactly one read-only SELECT (or WITH ... SELECT) statement."""
    stripped = sql.strip().rstrip(";").strip()
    if not stripped:
        return False
    # reject multiple statements (defends against `SELECT 1; DROP TABLE ...`)
    if ";" in stripped:
        return False
    if not re.match(r"^(SELECT|WITH)\b", stripped, re.IGNORECASE):
        return False
    if _FORBIDDEN_SQL.search(stripped):
        return False
    return True

# ============================================================
# 2. STATE — the data that flows between nodes
# ============================================================

class PipelineState(TypedDict):
    anomalies:     List[dict]        # from supervisor → loaded from DB
    sql_query:     Optional[str]     # from nl_to_sql  → generated by LLM
    trino_context: Optional[str]     # from nl_to_sql  → SQL result rows
    report:        Optional[str]     # from report_gen → markdown report
    confidence_score: Optional[int]  # from report_gen → parsed 0-100 score
    severity:      Optional[str]     # max severity in batch
    db_ids:        List[int]         # to mark processed at the end
    baseline_context: Optional[str]
    rag_context: str
    token_usage:      List[dict]    
    run_id:           str 

# Gemini 2.5 Flash pricing (as of 2026)
GEMINI_FLASH_INPUT_PRICE  = 0.075 / 1_000_000   # $0.075 per 1M input tokens
GEMINI_FLASH_OUTPUT_PRICE = 0.30  / 1_000_000   # $0.30 per 1M output tokens


def track_llm_call(response, agent_name: str) -> dict:
    """Extract token usage from a Gemini response and compute cost."""
    
    # Gemini returns usage in response.usage_metadata
    usage = response.usage_metadata or {}
    input_tokens  = usage.get("input_tokens", 0)
    output_tokens = usage.get("output_tokens", 0)
    total_tokens  = usage.get("total_tokens", input_tokens + output_tokens)

    cost = (input_tokens  * GEMINI_FLASH_INPUT_PRICE +
            output_tokens * GEMINI_FLASH_OUTPUT_PRICE)

    print(f"[token_tracker] {agent_name}: "
          f"in={input_tokens}, out={output_tokens}, "
          f"total={total_tokens}, cost=${cost:.6f}")

    return {
        "agent":         agent_name,
        "input_tokens":  input_tokens,
        "output_tokens": output_tokens,
        "total_tokens":  total_tokens,
        "cost_usd":      cost,
    }

def save_llm_usage(run_id: str, usage: dict):
    """Persist token usage to PostgreSQL."""
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("""
        INSERT INTO llm_usage 
            (run_id, agent, input_tokens, output_tokens, total_tokens, cost_usd)
        VALUES (%s, %s, %s, %s, %s, %s)
    """, (
        run_id,
        usage["agent"],
        usage["input_tokens"],
        usage["output_tokens"],
        usage["total_tokens"],
        usage["cost_usd"],
    ))
    conn.commit()
    conn.close()

def supervisor_node(state: PipelineState) -> PipelineState:
    """Poll anomalies table for unprocessed rows."""
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("""
        SELECT id, order_id, anomaly_type, severity, detail
        FROM anomalies
        WHERE processed = FALSE
        ORDER BY detected_at ASC
        LIMIT 10
    """)
    rows = cur.fetchall()
    conn.close()

    anomalies = [
        {
            "db_id":        r[0],
            "order_id":     r[1],
            "anomaly_type": r[2],
            "severity":     r[3],
            "detail":       r[4],
        }
        for r in rows
    ]

    severities = [a["severity"] for a in anomalies]
    max_severity = "high" if "high" in severities else \
                   "medium" if "medium" in severities else \
                   "low" if "low" in severities else None

    print(f"[supervisor] found {len(anomalies)} unprocessed anomalies")
    return {
        **state,
        "anomalies": anomalies,
        "db_ids":    [a["db_id"] for a in anomalies],
        "severity":  max_severity,
    }

def baseline_node(state: PipelineState) -> PipelineState:
    """Query historical stats to give LLM context on what 'normal' looks like."""
    conn = get_conn()
    cur  = conn.cursor()

    # 1. avg anomalies per day over last 7 days
    cur.execute("""
        SELECT 
            anomaly_type,
            COUNT(*) as total_last_7d,
            ROUND(COUNT(*) / 7.0, 1) as avg_per_day
        FROM anomalies
        WHERE detected_at > NOW() - INTERVAL '7 days'
        GROUP BY anomaly_type
        ORDER BY total_last_7d DESC
    """)
    anomaly_freq = cur.fetchall()

    # 2. peak hours for anomalies
    cur.execute("""
        SELECT 
            EXTRACT(HOUR FROM detected_at) as hour,
            COUNT(*) as count
        FROM anomalies
        WHERE detected_at > NOW() - INTERVAL '7 days'
        GROUP BY hour
        ORDER BY count DESC
        LIMIT 3
    """)
    peak_hours = cur.fetchall()

    # 3. today's anomaly count so far
    cur.execute("""
        SELECT COUNT(*) 
        FROM anomalies 
        WHERE detected_at::date = CURRENT_DATE
    """)
    today_count = cur.fetchone()[0]

    # 4. avg order volume (from orders_raw)
    cur.execute("""
        SELECT 
            COUNT(*) as total_orders,
            ROUND(AVG(total)::numeric, 2) as avg_order_value,
            COUNT(*) FILTER (WHERE status = 'failed') as failed_orders
        FROM orders_raw
        WHERE consumed_at > NOW() - INTERVAL '24 hours'
    """)
    order_stats = cur.fetchone()
    conn.close()

    # format it as a readable string for the LLM
    baseline_summary = f"""
    BASELINE CONTEXT (last 7 days):
    - Anomaly frequency by type:
    {chr(10).join([f"  * {r[0]}: {r[1]} total ({r[2]}/day avg)" for r in anomaly_freq])}

    - Peak anomaly hours: {[f"{int(r[0])}:00" for r in peak_hours]}
    - Anomalies detected today so far: {today_count}

    LAST 24H ORDER STATS:
    - Total orders: {order_stats[0]}
    - Avg order value: ${order_stats[1]}
    - Failed orders: {order_stats[2]}
"""

    print(f"[baseline] context built:\n{baseline_summary}")
    return {**state, "baseline_context": baseline_summary}

def retrieve_similar_reports(current_anomalies: list, top_k: int = 3) -> str:
    """Find past incident reports similar to current anomalies."""

    # build a search query from current anomaly types
    query_text = "anomalies: " + ", ".join([
        f"{a['anomaly_type']} on order {a['order_id']}"
        for a in current_anomalies
    ])

    # embed the query
    query_embedding = embedder.embed_query(query_text)

    conn = get_conn()
    cur  = conn.cursor()

    # cosine similarity search — returns closest past reports
    cur.execute("""
        SELECT 
            report_text,
            severity,
            anomaly_types,
            created_at,
            1 - (embedding <=> %s::vector) as similarity
        FROM incident_reports
        ORDER BY embedding <=> %s::vector
        LIMIT %s
    """, (query_embedding, query_embedding, top_k))

    rows = cur.fetchall()
    conn.close()

    if not rows:
        return "No similar past incidents found."

    # format for LLM context
    past_incidents = []
    for i, row in enumerate(rows, 1):
        report_text, severity, anomaly_types, created_at, similarity = row
        past_incidents.append(f"""
--- Past Incident {i} (similarity: {similarity:.2f}) ---
Date: {created_at.strftime('%Y-%m-%d %H:%M')}
Severity: {severity}
Anomaly types: {', '.join(anomaly_types)}
Report summary: {report_text[:500]}...
""")

    return "\n".join(past_incidents)

def rag_context_node(state: PipelineState) -> PipelineState:
    """Retrieve similar past incidents from vectorstore."""
    
    print(f"[rag] searching for similar past incidents...")
    past_context = retrieve_similar_reports(state["anomalies"])
    print(f"[rag] found context:\n{past_context[:200]}...\n")

    return {**state, "rag_context": past_context}

def nl_to_sql_node(state: PipelineState) -> PipelineState:
    """LLM generates a SQL query to investigate the anomalies, then runs it."""

    anomaly_summary = "\n".join([
        f"- {a['anomaly_type']} on order {a['order_id']} (severity: {a['severity']})"
        for a in state["anomalies"]
    ])

    baseline_context = state.get("baseline_context") or ""

    system = f"""You are a SQL expert investigating data anomalies in an
e-commerce orders pipeline. Given a list of anomalies, write ONE PostgreSQL
query against the orders_raw table to find context about what happened.

Table schema:
  orders_raw(id, event, customer_id, total, status, raw_payload, consumed_at)

{baseline_context}

Use the baseline context above to make your SQL more targeted.
For example if payment_failed is spiking, focus the query there.
Return ONLY the SQL query, no markdown, no explanation.
"""

    response = sql_agent.invoke([
        SystemMessage(content=system),
        HumanMessage(content=f"Anomalies detected:\n{anomaly_summary}\n\nGenerate the SQL.")
    ])
    sql = response.content.strip()
    if sql.startswith("```"):
        sql = sql.split("```")[1]          # remove opening ```sql
        sql = sql.lstrip("sql").strip()  
    print(f"[nl_to_sql] generated SQL:\n{sql}\n")
    usage = track_llm_call(response, agent_name="sql_agent")
    save_llm_usage(state["run_id"], usage)
    state["token_usage"].append(usage)

    # Defense in depth: reject anything that isn't a single read-only SELECT
    # BEFORE touching the DB. The SQL is LLM-generated from external (Kafka)
    # input, so it must be treated as untrusted.
    if not is_safe_select(sql):
        context = "Query rejected: only a single read-only SELECT is permitted."
        print(f"[nl_to_sql] {context}")
        return {**state, "sql_query": sql, "trino_context": context}

    # run it on a read-only connection (second layer: the DB itself blocks writes)
    conn = get_readonly_conn()
    cur  = conn.cursor()
    try:
        cur.execute(sql)
        rows = cur.fetchall()
        cols = [d[0] for d in cur.description]
        context = "\n".join([str(dict(zip(cols, r))) for r in rows])
    except Exception as e:
        context = f"Query failed: {e}"
    conn.close()

    return {**state, "sql_query": sql, "trino_context": context}


def report_generator_node(state: PipelineState) -> PipelineState:
    """LLM writes a markdown incident report."""

    system = """You are an on-call data engineer writing an incident report.
Be concise. Include: what happened, likely root cause, recommended action.
Output clean markdown.
At the end, add a confidence score (0-100) for your root cause assessment
and one sentence explaining why you're uncertain if score < 70.
"""

    user = f"""Anomalies:
{json.dumps(state['anomalies'], indent=2, default=str)}

Investigation SQL:
{state['sql_query']}

Query results:
{state['trino_context']}

SIMILAR PAST INCIDENTS (use these to identify patterns):
{state['rag_context']}

Write the incident report."""

    response = report_agent.invoke([SystemMessage(content=system), HumanMessage(content=user)])
    report = response.content
    usage = track_llm_call(response, agent_name="report_agent")
    save_llm_usage(state["run_id"], usage)
    state["token_usage"].append(usage)
    print(f"[report_generator]\n{report}\n")
    confidence = parse_confidence_score(report)
    print(f"[report_generator] parsed confidence score: {confidence}")
    save_report_to_vectorstore(report, state['severity'], state["anomalies"], confidence)
    return {**state, "report": report, "confidence_score": confidence}


def parse_confidence_score(report: str) -> Optional[int]:
    """Extract the LLM's 0-100 confidence score from the report markdown."""
    m = re.search(r"[Cc]onfidence\s*Score[^0-9]{0,20}(\d{1,3})", report)
    if not m:
        return None
    score = int(m.group(1))
    return score if 0 <= score <= 100 else None


def save_report_to_vectorstore(report: str, severity: str, anomalies: list, confidence_score: Optional[int] = None):
    """Embed and store the incident report in pgvector."""

    # generate embedding for the report
    embedding = embedder.embed_query(report)
    anomaly_types = list(set([a["anomaly_type"] for a in anomalies]))

    conn = get_conn()
    cur  = conn.cursor()
    cur.execute("""
        INSERT INTO incident_reports
            (severity, anomaly_types, report_text, embedding, confidence_score)
        VALUES (%s, %s, %s, %s, %s)
    """, (
        severity,
        anomaly_types,
        report,
        embedding,       # pgvector accepts python list directly
        confidence_score
    ))
    conn.commit()
    conn.close()
    print(f"[vectorstore] report embedded and saved")


def alert_dispatcher_node(state: PipelineState) -> PipelineState:
    """Send Slack + save report + mark anomalies as processed."""

    # 1. save report to file (later: S3)
    fname = f"incidents/incident_{int(time.time())}.md"
    os.makedirs("incidents", exist_ok=True)
    with open(fname, "w") as f:
        f.write(state["report"])
    print(f"[dispatcher] report saved to {fname}")

    # 2. (stub) send Slack — add real webhook later
    # requests.post(SLACK_WEBHOOK, json={"text": state["report"]})

    # 3. mark anomalies as processed
    conn = get_conn()
    cur  = conn.cursor()
    cur.execute(
        "UPDATE anomalies SET processed = TRUE WHERE id = ANY(%s)",
        (state["db_ids"],)
    )
    conn.commit()
    conn.close()
    print(f"[dispatcher] marked {len(state['db_ids'])} anomalies as processed")

    total_tokens = sum(u["total_tokens"] for u in state["token_usage"])
    total_cost   = sum(u["cost_usd"]     for u in state["token_usage"])
    n_anomalies  = len(state["db_ids"])
    cost_per_anomaly = total_cost / n_anomalies if n_anomalies else 0

    print(f"\n[cost_summary] run {state['run_id']}")
    print(f"  total tokens:     {total_tokens}")
    print(f"  total cost:       ${total_cost:.6f}")
    print(f"  anomalies:        {n_anomalies}")
    print(f"  cost per anomaly: ${cost_per_anomaly:.6f}")

    return state

def route_on_anomalies(state: PipelineState) -> str:
    if state["anomalies"]:
        return "investigate"
    return "wait"


# ============================================================
# 5. BUILD THE GRAPH
# ============================================================

graph = StateGraph(PipelineState)
graph.add_node("supervisor",       supervisor_node)
graph.add_node("baseline",         baseline_node)      # ← add
graph.add_node("nl_to_sql",        nl_to_sql_node)
graph.add_node("report_generator", report_generator_node)
graph.add_node("alert_dispatcher", alert_dispatcher_node)
graph.add_node("rag_context",rag_context_node)

graph.set_entry_point("supervisor")

graph.add_conditional_edges(
    "supervisor",
    route_on_anomalies,
    {
        "investigate": "baseline",
        "wait":        END,
    }
)
graph.add_edge("baseline",         "nl_to_sql")
graph.add_edge("nl_to_sql",        "rag_context")
graph.add_edge("rag_context",        "report_generator")
graph.add_edge("report_generator", "alert_dispatcher")
graph.add_edge("alert_dispatcher", END)

app = graph.compile()


if __name__ == "__main__":
    while True:
        print("\n" + "=" * 60)
        print(f"running graph at {time.strftime('%H:%M:%S')}")
        print("=" * 60)
        app.invoke({
            "run_id":   str(uuid.uuid4())[:8],
            "anomalies": [],
            "sql_query": None,
            "trino_context": None,
            "report": None,
            "severity": None,
            "db_ids": [],
            "baseline_context": None,
            "token_usage": [],
        })
        time.sleep(30)